export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
export const DELETE_LOGOUT = "DELETE_LOGOUT";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESST";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const SERVER_ERROR = 'SERVER_ERROR';


export const GET_CONTAINERS_REQUEST = "GET_CONTAINERS_REQUEST";
export const GET_CONTAINERS_SUCCESS = "GET_CONTAINERS_SUCCESS";
export const GET_CONTAINERS_ERROR = "GET_CONTAINERS_ERROR";

export const GET_CONTAINER_REQUEST = "GET_CONTAINER_REQUEST";
export const GET_CONTAINER_SUCCESS = "GET_CONTAINER_SUCCESS";
export const GET_CONTAINER_ERROR = "GET_CONTAINER_ERROR";

export const ADD_CONTAINER_REQUEST = "ADD_CONTAINER_REQUEST";
export const ADD_CONTAINER_SUCCESS = "ADD_CONTAINER_SUCCESS";
export const ADD_CONTAINER_ERROR = "ADD_CONTAINER_ERROR";

export const UPDATE_CONTAINER_REQUEST = "UPDATE_CONTAINER_REQUEST";
export const UPDATE_CONTAINER_SUCCESS = "UPDATE_CONTAINER_SUCCESS";
export const UPDATE_CONTAINER_ERROR = "UPDATE_CONTAINER_ERROR";

export const DELETE_CONTAINER_REQUEST = "DELETE_CONTAINER_REQUEST";
export const DELETE_CONTAINER_SUCCESS = "DELETE_CONTAINER_SUCCESS";
export const DELETE_CONTAINER_ERROR = "DELETE_CONTAINER_ERROR";


export const GET_PALLETS_REQUEST = "GET_PALLETS_REQUEST";
export const GET_PALLETS_SUCCESS = "GET_PALLETS_SUCCESS";
export const GET_PALLETS_ERROR = "GET_PALLETS_ERROR";

export const GET_PALLET_REQUEST = "GET_PALLET_REQUEST";
export const GET_PALLET_SUCCESS = "GET_PALLET_SUCCESS";
export const GET_PALLET_ERROR = "GET_PALLET_ERROR";


export const GET_NEW_PALLET_REQUEST = "GET_NEW_PALLET_REQUEST";
export const GET_NEW_PALLET_SUCCESS = "GET_NEW_PALLET_SUCCESS";
export const GET_NEW_PALLET_ERROR = "GET_NEW_PALLET_ERROR";


export const ADD_PALLET_REQUEST = "ADD_PALLET_REQUEST";
export const ADD_PALLET_SUCCESS = "ADD_PALLET_SUCCESS";
export const ADD_PALLET_ERROR = "ADD_PALLET_ERROR";

export const UPDATE_PALLET_REQUEST = "UPDATE_PALLET_REQUEST";
export const UPDATE_PALLET_SUCCESS = "UPDATE_PALLET_SUCCESS";
export const UPDATE_PALLET_ERROR = "UPDATE_PALLET_ERROR";


export const DELETE_PALLET_REQUEST = "DELETE_PALLET_REQUEST";
export const DELETE_PALLET_SUCCESS = "DELETE_PALLET_SUCCESS";
export const DELETE_PALLET_ERROR = "DELETE_PALLET_ERROR";


export const GET_PACKAGES_REQUEST = "GET_PACKAGES_REQUEST";
export const GET_PACKAGES_SUCCESS = "GET_PACKAGES_SUCCESS";
export const GET_PACKAGES_ERROR = "GET_PACKAGES_ERROR";

export const GET_PACKAGE_REQUEST = "GET_PACKAGE_REQUEST";
export const GET_PACKAGE_SUCCESS = "GET_PACKAGE_SUCCESS";
export const GET_PACKAGE_ERROR = "GET_PACKAGE_ERROR";

export const ADD_PACKAGE_REQUEST = "ADD_PACKAGE_REQUEST";
export const ADD_PACKAGE_SUCCESS = "ADD_PACKAGE_SUCCESS";
export const ADD_PACKAGE_ERROR = "ADD_PACKAGE_ERROR";

export const UPDATE_PACKAGE_REQUEST = "UPDATE_PACKAGE_REQUEST";
export const UPDATE_PACKAGE_SUCCESS = "UPDATE_PACKAGE_SUCCESS";
export const UPDATE_PACKAGE_ERROR = "UPDATE_PACKAGE_ERROR";


export const DELETE_PACKAGE_REQUEST = "DELETE_PACKAGE_REQUEST";
export const DELETE_PACKAGE_SUCCESS = "DELETE_PACKAGE_SUCCESS";
export const DELETE_PACKAGE_ERROR = "DELETE_PACKAGE_ERROR";


export const GET_PACKAGETYPE_SUCCESS = 'GET_PACKAGETYPE_SUCCESS';
export const GET_PACKAGETYPE_ERROR = 'GET_PACKAGETYPE_ERROR';

export const ADD_PACKAGETYPE_SUCCESS = 'ADD_PACKAGETYPE_SUCCESS';
export const ADD_PACKAGETYPE_ERROR = 'ADD_PACKAGETYPE_ERROR';


export const GET_CONTAINER_MANIFEST_REQUEST = "GET_CONTAINER_MANIFEST_REQUEST";
export const GET_CONTAINER_MANIFEST_SUCCESS = "GET_CONTAINER_MANIFEST_SUCCESS";
export const GET_CONTAINER_MANIFEST_ERROR = "GET_CONTAINER_MANIFEST_ERROR";

export const GET_PALLET_MANIFEST_REQUEST = "GET_PALLET_MANIFEST_REQUEST";
export const GET_PALLET_MANIFEST_SUCCESS = "GET_PALLET_MANIFEST_SUCCESS";
export const GET_PALLET_MANIFEST_ERROR = "GET_PALLET_MANIFEST_ERROR";

export const VALIDATE_EMAIL_REQUEST = "VALIDATE_EMAIL_REQUEST";
export const VALIDATE_EMAIL_SUCCESS = "VALIDATE_EMAIL_SUCCESST";
export const VALIDATE_EMAIL_ERROR = "VALIDATE_EMAIL_ERROR";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

export const GET_PACKAGE_PKG_NO_REQUEST = "GET_PACKAGE_PKG_NO_REQUEST";
export const GET_PACKAGE_PKG_NO_SUCCESS = "GET_PACKAGE_PKG_NO_SUCCESS";
export const GET_PACKAGE_PKG_NO_ERROR = "GET_PACKAGE_PKG_NO_ERROR";

export const GET_SELECTED_HWB_INFO_REQUEST = "GET_SELECTED_HWB_INFO_REQUEST";
export const GET_SELECTED_HWB_INFO_SUCCESS = "GET_SELECTED_HWB_INFO_SUCCESS";
export const GET_SELECTED_HWB_INFO_ERROR = "GET_SELECTED_HWB_INFO_ERROR";


export const GET_DELIVERIES_REQUEST = "GET_DELIVERIES_REQUEST";
export const GET_DELIVERIES_SUCCESS = "GET_DELIVERIES_SUCCESS";
export const GET_DELIVERIES_ERROR = "GET_DELIVERIES_ERROR";

export const GET_DELIVERY_REQUEST = "GET_DELIVERY_REQUEST";
export const GET_DELIVERY_SUCCESS = "GET_DELIVERY_SUCCESS";
export const GET_DELIVERY_ERROR = "GET_DELIVERY_ERROR";

export const ADD_DELIVERY_REQUEST = "ADD_DELIVERY_REQUEST";
export const ADD_DELIVERY_SUCCESS = "ADD_DELIVERY_SUCCESS";
export const ADD_DELIVERY_ERROR = "ADD_DELIVERY_ERROR";

export const UPDATE_DELIVERY_REQUEST = "UPDATE_DELIVERY_REQUEST";
export const UPDATE_DELIVERY_SUCCESS = "UPDATE_DELIVERY_SUCCESS";
export const UPDATE_DELIVERY_ERROR = "UPDATE_DELIVERY_ERROR";

export const DELETE_DELIVERY_REQUEST = "DELETE_DELIVERY_REQUEST";
export const DELETE_DELIVERY_SUCCESS = "DELETE_DELIVERY_SUCCESS";
export const DELETE_DELIVERY_ERROR = "DELETE_DELIVERY_ERROR";


export const GET_LOCATIONS_REQUEST = "GET_LOCATIONS_REQUEST";
export const GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS";
export const GET_LOCATIONS_ERROR =   "GET_LOCATIONS_ERROR";

export const GET_LOCATION_REQUEST = "GET_LOCATION_REQUEST";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATION_ERROR =   "GET_LOCATION_ERROR";

export const ADD_LOCATION_REQUEST = "ADD_LOCATION_REQUEST";
export const ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS";
export const ADD_LOCATION_ERROR =   "ADD_LOCATION_ERROR";

export const UPDATE_LOCATION_REQUEST = "UPDATE_LOCATION_REQUEST";
export const UPDATE_LOCATION_SUCCESS = "UPDATE_LOCATION_SUCCESS";
export const UPDATE_LOCATION_ERROR =   "UPDATE_LOCATION_ERROR";

export const DELETE_LOCATION_REQUEST = "DELETE_LOCATION_REQUEST";
export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
export const DELETE_LOCATION_ERROR =   "DELETE_LOCATION_ERROR";


export const SEND_EMAIL_LOCATION_REQUEST = "SEND_EMAIL_LOCATION_REQUEST";
export const SEND_EMAIL_LOCATION_SUCCESS = "SEND_EMAIL_LOCATION_SUCCESS";
export const SEND_EMAIL_LOCATION_ERROR =   "SEND_EMAIL_LOCATION_ERROR";



export const GET_DROPOFFS_REQUEST = "GET_DROPOFFS_REQUEST";
export const GET_DROPOFFS_SUCCESS = "GET_DROPOFFS_SUCCESS";
export const GET_DROPOFFS_ERROR =   "GET_DROPOFFS_ERROR";

export const GET_DROPOFF_REQUEST = "GET_DROPOFF_REQUEST";
export const GET_DROPOFF_SUCCESS = "GET_DROPOFF_SUCCESS";
export const GET_DROPOFF_ERROR =   "GET_DROPOFF_ERROR";

export const ADD_DROPOFF_REQUEST = "ADD_DROPOFF_REQUEST";
export const ADD_DROPOFF_SUCCESS = "ADD_DROPOFF_SUCCESS";
export const ADD_DROPOFF_ERROR =   "ADD_DROPOFF_ERROR";

export const UPDATE_DROPOFF_REQUEST = "UPDATE_DROPOFF_REQUEST";
export const UPDATE_DROPOFF_SUCCESS = "UPDATE_DROPOFF_SUCCESS";
export const UPDATE_DROPOFF_ERROR =   "UPDATE_DROPOFF_ERROR";

export const DELETE_DROPOFF_REQUEST = "DELETE_DROPOFF_REQUEST";
export const DELETE_DROPOFF_SUCCESS = "DELETE_DROPOFF_SUCCESS";
export const DELETE_DROPOFF_ERROR =   "DELETE_DROPOFF_ERROR";

// export const GET_PACKAGE_PKG_NO_REQUEST = "GET_PACKAGE_PKG_NO_REQUEST";
// export const GET_PACKAGE_PKG_NO_SUCCESS = "GET_PACKAGE_PKG_NO_SUCCESS";
// export const GET_PACKAGE_PKG_NO_ERROR = "GET_PACKAGE_PKG_NO_ERROR";

export const GET_SELECTED_HWB_INFO_FOR_DROPOFF_REQUEST = "GET_SELECTED_HWB_INFO_FOR_DROPOFF_REQUEST";
export const GET_SELECTED_HWB_INFO_FOR_DROPOFF_SUCCESS = "GET_SELECTED_HWB_INFO_FOR_DROPOFF_SUCCESS";
export const GET_SELECTED_HWB_INFO_FOR_DROPOFF_ERROR = "GET_SELECTED_HWB_INFO_FOR_DROPOFF_ERROR";

export const GET_SELECTED_SCANNED_HWB_INFO_FOR_DROPOFF_REQUEST = "GET_SELECTED_SCANNED_HWB_INFO_FOR_DROPOFF_REQUEST";
export const GET_SELECTED_SCANNED_HWB_INFO_FOR_DROPOFF_SUCCESS = "GET_SELECTED_SCANNED_HWB_INFO_FOR_DROPOFF_SUCCESS";
export const GET_SELECTED_SCANNED_HWB_INFO_FOR_DROPOFF_ERROR = "GET_SELECTED_SCANNED_HWB_INFO_FOR_DROPOFF_ERROR";